on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: ratloopz
          label: welcome
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<b>An invitation has been sent to join ratloopz.</b><br><br>Check your profile menu → “Your organizations”. After accepting, set your membership to public so it shows on your profile.'
          existingMemberMessage: 'You are already a member of this organization.'
        env:
          INVITE_TOKEN: ${{ secrets.ORG_INVITE_TOKEN_NEW }}
